# Generated by Django 4.2.7 on 2024-05-27 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("public", "0002_tiponovedadrpbf"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_hash", models.CharField(max_length=32)),
                ("date_inserted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RPBF_PERIODOS",
            fields=[
                (
                    "PERIODO",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("FECHA_INCIAL", models.DateField()),
                ("FECHA_FINAL", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="RpbfCandidatos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tpidentif", models.CharField(max_length=3)),
                ("nroIdentif", models.CharField(max_length=20)),
                ("fondo", models.CharField(max_length=2)),
                ("fechaCreacion", models.DateTimeField()),
                ("fechaCancelacion", models.DateTimeField()),
                (
                    "tipoNovedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="public.tiponovedadrpbf",
                    ),
                ),
            ],
            options={
                "db_table": "rpbf_candidatos",
            },
        ),
        migrations.CreateModel(
            name="RPBF_HISTORICO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TIPO_IDENTIF", models.CharField(max_length=3)),
                ("NRO_IDENTIF", models.CharField(max_length=20)),
                ("FONDO", models.CharField(max_length=2)),
                ("TIPO_NOVEDAD", models.CharField(max_length=2)),
                ("PORCENTAJE_SALDO", models.CharField(blank=True, max_length=100)),
                ("FECHA_CREACION", models.CharField(blank=True, max_length=10)),
                ("FECHA_CANCELACION", models.CharField(blank=True, max_length=10)),
                (
                    "PERIODO_REPORTADO",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beneficiario_final.rpbf_periodos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Beneficiario_Reporte_Dian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Id_Cliente", models.CharField(max_length=255)),
                ("Periodo", models.CharField(max_length=255)),
                ("Tipo_Producto", models.CharField(max_length=255)),
                (
                    "Tipo_Novedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="public.tiponovedadrpbf",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="rpbf_historico",
            constraint=models.UniqueConstraint(
                fields=(
                    "TIPO_IDENTIF",
                    "NRO_IDENTIF",
                    "FONDO",
                    "PERIODO_REPORTADO",
                    "TIPO_NOVEDAD",
                ),
                name="pk_rpbf_historico",
            ),
        ),
        migrations.AddConstraint(
            model_name="beneficiario_reporte_dian",
            constraint=models.UniqueConstraint(
                fields=("Id_Cliente", "Tipo_Novedad", "Tipo_Producto"),
                name="unique_identificacion_beneficiario",
            ),
        ),
    ]
