# Generated by Django 4.2.7 on 2023-12-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Novedad',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiario_Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('period', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('type_product', models.CharField(max_length=255)),
                ('Tipo_Novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario_final.tipo_novedad')),
            ],
        ),
        migrations.AddConstraint(
            model_name='beneficiario_reporte',
            constraint=models.UniqueConstraint(fields=('client_id', 'Tipo_Novedad', 'type_product'), name='unique_identificacion_beneficiario'),
        ),
    ]
