# Generated by Django 4.2.7 on 2024-06-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiario_final", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsecutivosRpbf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fondo", models.CharField(max_length=3)),
                ("consecutivo", models.IntegerField(db_column="consecutivo")),
            ],
            options={
                "db_table": "rpbf_consecutivos",
            },
        ),
    ]
