# Generated by Django 4.2.7 on 2023-12-26 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario_final', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario_Reporte_Dian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Cliente', models.CharField(max_length=255)),
                ('Fecha_Añadido', models.DateTimeField(auto_now_add=True)),
                ('Fecha_Creado', models.DateTimeField(auto_now_add=True)),
                ('Periodo', models.CharField(max_length=255)),
                ('Activo', models.BooleanField(default=True)),
                ('Tipo_Producto', models.CharField(max_length=255)),
                ('Tipo_Novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario_final.tipo_novedad')),
            ],
        ),
        migrations.DeleteModel(
            name='Beneficiario_Reporte',
        ),
        migrations.AddConstraint(
            model_name='beneficiario_reporte_dian',
            constraint=models.UniqueConstraint(fields=('Id_Cliente', 'Tipo_Novedad', 'Tipo_Producto'), name='unique_identificacion_beneficiario'),
        ),
    ]
