# Generated by Django 4.2.7 on 2024-05-27 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0002_tiponovedadrpbf"),
        ("beneficiario_final", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RpbfHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.CharField(max_length=6)),
                ("fondo", models.CharField(max_length=2)),
                ("bepjtit", models.CharField(max_length=2)),
                ("bepjben", models.CharField(max_length=2)),
                ("bepjcon", models.CharField(max_length=2)),
                ("bepjrl", models.CharField(max_length=2)),
                ("bespjfcp", models.CharField(max_length=2)),
                ("bespjf", models.CharField(max_length=2)),
                ("bespjcf", models.CharField(max_length=2)),
                ("bespjfb", models.CharField(max_length=2)),
                ("bespjcfe", models.CharField(max_length=2)),
                ("tdocben", models.CharField(max_length=2)),
                ("niben", models.CharField(max_length=20)),
                ("paexben", models.CharField(max_length=4)),
                ("nitben", models.CharField(max_length=20)),
                ("paexnitben", models.CharField(max_length=4)),
                ("pape", models.CharField(max_length=60)),
                ("sape", models.CharField(max_length=60)),
                ("pnom", models.CharField(max_length=60)),
                ("onom", models.CharField(max_length=60)),
                ("fecnac", models.CharField(max_length=10)),
                ("panacb", models.CharField(max_length=4)),
                ("pnacion", models.CharField(max_length=4)),
                ("paresb", models.CharField(max_length=4)),
                ("dptoben", models.CharField(max_length=2)),
                ("munben", models.CharField(max_length=3)),
                ("dirben", models.CharField(max_length=250)),
                ("codpoben", models.CharField(max_length=10)),
                ("emailben", models.CharField(max_length=50)),
                ("feiniben", models.CharField(max_length=10)),
                ("fecfinben", models.CharField(max_length=10)),
                ("tnov", models.CharField(max_length=1)),
                (
                    "tipoNovedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="public.tiponovedadrpbf",
                    ),
                ),
            ],
            options={
                "db_table": "rpbf_historico",
            },
        ),
        # migrations.DeleteModel(
        #     name="RPBF_HISTORICO",
        # ),
        # migrations.DeleteModel(
        #     name="RPBF_PERIODOS",
        # ),
    ]
