# Generated by Django 5.0.6 on 2024-06-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiario_final", "0002_rpbfhistorico_delete_rpbf_historico_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RPBF_HISTORICO",
        ),
        migrations.DeleteModel(
            name="RPBF_PERIODOS",
        ),
    ]
