# Generated by Django 4.2.7 on 2024-01-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario_final', '0002_beneficiario_reporte_dian_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=32)),
                ('date_inserted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
