# Generated by Django 4.2.7 on 2024-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiario_final", "0002_rpbfhistorico_cargue"),
    ]

    operations = [
        migrations.AddField(
            model_name="rpbfcandidatos",
            name="tpIdentif",
            field=models.CharField(default=13, max_length=3),
            preserve_default=False,
        ),
    ]
