# Generated by Django 4.2.7 on 2024-01-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario_final', '0003_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPBF_PERIODOS',
            fields=[
                ('PERIODO', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('FECHA_INCIAL', models.DateField()),
                ('FECHA_FINAL', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='beneficiario_reporte_dian',
            name='Activo',
        ),
        migrations.RemoveField(
            model_name='beneficiario_reporte_dian',
            name='Fecha_Añadido',
        ),
        migrations.RemoveField(
            model_name='beneficiario_reporte_dian',
            name='Fecha_Creado',
        ),
        migrations.CreateModel(
            name='RPBF_HISTORICO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIPO_IDENTIF', models.CharField(max_length=3)),
                ('NRO_IDENTIF', models.CharField(max_length=20)),
                ('FONDO', models.CharField(max_length=2)),
                ('TIPO_NOVEDAD', models.CharField(max_length=2)),
                ('PERIODO_REPORTADO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario_final.rpbf_periodos')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rpbf_historico',
            constraint=models.UniqueConstraint(fields=('TIPO_IDENTIF', 'NRO_IDENTIF', 'FONDO', 'PERIODO_REPORTADO', 'TIPO_NOVEDAD'), name='pk_rpbf_historico'),
        ),
    ]
