# Generated by Django 4.2.7 on 2024-01-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario_final', '0004_rpbf_periodos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpbf_periodos',
            name='PERIODO',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
