# Generated by Django 4.2.7 on 2024-02-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiario_final", "0005_alter_rpbf_periodos_periodo"),
    ]

    operations = [
        migrations.AddField(
            model_name="rpbf_historico",
            name="FECHA_CANCELACION",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="rpbf_historico",
            name="FECHA_CREACION",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="rpbf_historico",
            name="PORCENTAJE_SALDO",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
