query_rendir='''
WITH UBICACION AS(
    SELECT * FROM GE_TCIUD 
    INNER JOIN GE_TDEPTO ON DEPTO_DEPTO=CIUD_DEPTO
    INNER JOIN GE_TPAIS ON PAIS_PAIS=DEPTO_PAIS
)
SELECT DISTINCT
'4'  AS BEPJTIT,
'8'  AS BEPJEBEN,
'N'  AS BEPJCON,
'N'  AS BEPJRL,
'S'  AS BEPJFCP,
'N'  AS BEPJF,
'N'  AS BEPJCF,
'N'  AS BEPJFB,
'N'  AS BEPJCFE,
''   AS BECESPJ,
CASE 
    WHEN  CLNTE_TPIDENTIF='CC' THEN '13' 
    WHEN  CLNTE_TPIDENTIF='TI' THEN '12'
    WHEN  CLNTE_TPIDENTIF='CE' THEN '22'
    WHEN  CLNTE_TPIDENTIF='CE' THEN '22'
    WHEN  CLNTE_TPIDENTIF='PA' THEN '41'
    WHEN  CLNTE_TPIDENTIF='RC' THEN '11'
    WHEN  CLNTE_TPIDENTIF='PEP' THEN '47' 
ELSE 'CC' END               AS TIPO_DE_DOCUMENTO,
CLNTE_NROIDENT              AS NUMERO_DE_IDENTIF,
PAIS_EXPEDICION             AS PAIS_EXP_IDENTIF,
CLNTE_NROIDENT              AS NUMERO_IDENTIF_TRIBUTARIA,
PAIS_EXPEDICION             AS PAIS_EXP_TRIBUTARIA,
CLNAT_PAPELLIDO             AS PRIMER_APELLIDO,
CLNAT_SAPELLIDO             AS SEGUNDO_APELLIDO,
CLNAT_PNOMBRE               AS PRIMER_NOMBRE,
CLNAT_SNOMBRE               AS OTROS_NOMBRES,
TO_CHAR(CLNAT_FECHA_NACIMIENTO,'YYYY-MM-DD')  AS FECHA_NACIMIENTO,
PAIS_NACIMIENTO             AS PAIS_NACIMIENTO,
PAIS_NACIONALIDAD           AS PAIS_NACIONALIDAD,
PAIS_RESIDENCIA             AS PAIS_RESIDENCIA,
DEPARTAMENTO_NOTIFICACION   AS DEPARTAMENTO_NOTIFICACION,
MUNICIPIO_NOTIFICACION      AS MUNICIPIO_NOTIFICACION,
DIRECCION_NOTIFICACION      AS DIRECCION_NOTIFICACION,
CODIGO_POSTAL               AS CODIGO_POSTAL,
CORREO_NOTIFICACION         AS CORREO_NOTIFICACION,
PORCENTAJE_SALDO                          AS PPPJEPJ,
''            AS PBPJEPJ,
MAX_FECCRE                  AS FECINBIBEN ,
''                          AS FECFINBEN,
'1'                         AS TNOV

FROM (
    SELECT CLNTE_TPIDENTIF,CLNTE_NROIDENT,CIUD_EXP.PAIS_COD_DIAN PAIS_EXPEDICION,
    AUXI_DIGITO,CIUD_EXP.PAIS_COD_DIAN,CLNAT_PAPELLIDO,CLNAT_SAPELLIDO,
    CLNAT_PNOMBRE,CLNAT_SNOMBRE,CLNAT_FECHA_NACIMIENTO,CIUD_NAC.PAIS_COD_DIAN PAIS_NACIMIENTO,PAIS_NACIO.PAIS_COD_DIAN PAIS_NACIONALIDAD,
    PAIS_RES.PAIS_COD_DIAN PAIS_RESIDENCIA,PAIS_RES.DEPTO_DEPTO DEPARTAMENTO_NOTIFICACION,
    PAIS_RES.CIUD_DANE MUNICIPIO_NOTIFICACION,PAIS_RES.DIREC_DIRECCION DIRECCION_NOTIFICACION,CODIGO_POSTAL,EMAIL_DIRECCION AS CORREO_NOTIFICACION,TO_CHAR(MAX_FECCRE,'YYYY-MM-DD') AS MAX_FECCRE,DIREC_BARRIO,
    PORCENTAJE_SALDO
    
    
    FROM  
        (
            --4927
            SELECT  PTPL_FDEI,ROUND(SUM(NVL(ACDI_SALDO,0))*100/(SELECT SUM(ACDI_SALDO) FROM SF_TACDI
                WHERE ACDI_FECCIE=&&fecha_corte ),5) PORCENTAJE_SALDO ,MAX(PTPL_FECCRE) MAX_FECCRE FROM SF_TPTPL  
            INNER JOIN SF_TPLAN  ON PLAN_PLAN=PTPL_PLAN 
            INNER JOIN SF_TFDEI ON FDEI_FDEI=PTPL_FDEI
            LEFT JOIN (SELECT * FROM SF_TACDI
                        WHERE ACDI_FECCIE=&&fecha_corte) ON ACDI_PLAN=PLAN_PLAN
            WHERE PTPL_FOND=ACDI_FOND AND 
            TRUNC(PTPL_FECCRE)<=TRUNC(&&fecha_corte) AND 
            (TRUNC(PLAN_FECCAN) > TRUNC(&&fecha_corte) OR PLAN_FECCAN IS NULL) AND
            FDEI_TPID NOT IN ('A','F')
            GROUP BY PTPL_FDEI
            ORDER BY 2 DESC
        ) C1 
          INNER JOIN SF_TPTPL C2 ON C1.PTPL_FDEI=C2.PTPL_FDEI AND C1.MAX_FECCRE=C2.PTPL_FECCRE 
          INNER JOIN CL_TCLNTE  ON CLNTE_NROIDENT=TO_CHAR(C1.PTPL_FDEI)
          INNER JOIN CL_TCLNAT  ON CLNAT_NROIDENT=CLNTE_NROIDENT
          INNER JOIN CL_TCOD_POSTAL ON ID_CLNTE=CLNAT_NROIDENT
          LEFT JOIN GE_TAUXIL ON AUXI_NIT=C1.PTPL_FDEI
          LEFT JOIN UBICACION CIUD_EXP ON CLNAT_CIUD_EXPEDICION=CIUD_EXP.CIUD_CIUD
          LEFT JOIN UBICACION CIUD_NAC ON CLNAT_CIUD_NACIMIENTO=CIUD_NAC.CIUD_CIUD
          LEFT JOIN CL_TCNLD ON CNAT_NROIDENTF=CLNTE_NROIDENT
          LEFT JOIN GE_TPAIS PAIS_NACIO ON PAIS_NACIO.PAIS_PAIS=CNAT_NACIONALIDAD_1        
          LEFT JOIN (
                        SELECT C.*,A.* FROM CL_TDIREC A INNER JOIN                          
                            (
                                SELECT DIREC_TPIDENTIF,DIREC_NROIDENT,MAX(DIREC_DIREC) MAX_DIREC FROM CL_TDIREC WHERE DIREC_TPDIR='RES' GROUP BY DIREC_TPIDENTIF,DIREC_NROIDENT                            
                            ) B ON A.DIREC_NROIDENT=B.DIREC_NROIDENT AND DIREC_DIREC=MAX_DIREC AND A.DIREC_TPIDENTIF=B.DIREC_TPIDENTIF
                        LEFT JOIN UBICACION C ON C.CIUD_CIUD=DIREC_CIUD

                    ) PAIS_RES ON PAIS_RES.DIREC_NROIDENT=CLNTE_NROIDENT AND PAIS_RES.DIREC_TPIDENTIF=CLNTE_TPIDENTIF
          LEFT JOIN (
                        SELECT DISTINCT A.EMAIL_TPIDENTIF,A.EMAIL_NROIDENT,A.EMAIL_DIRECCION FROM CL_TEMAIL A INNER JOIN 
                            (
                                SELECT EMAIL_TPIDENTIF,EMAIL_NROIDENT,MAX(EMAIL_EMAIL) MAX_EMA FROM CL_TEMAIL GROUP BY EMAIL_TPIDENTIF,EMAIL_NROIDENT

                            ) B ON A.EMAIL_EMAIL=B.MAX_EMA
                    ) EMA ON EMA.EMAIL_NROIDENT=CLNTE_NROIDENT AND EMA.EMAIL_TPIDENTIF=CLNTE_TPIDENTIF          
)

WHERE (
--VALIDACIONES CORREO
CORREO_NOTIFICACION IS NOT NULL AND CORREO_NOTIFICACION LIKE '%@%' AND CORREO_NOTIFICACION IS NOT NULL AND CORREO_NOTIFICACION not in ('DESCONOCIDO','0')
--VALIDACIONES NOTIFICACION 
AND DEPARTAMENTO_NOTIFICACION IS NOT NULL AND MUNICIPIO_NOTIFICACION<>'-' AND DIRECCION_NOTIFICACION IS NOT NULL AND MUNICIPIO_NOTIFICACION IS NOT NULL 
AND CODIGO_POSTAL IS NOT NULL AND PAIS_RESIDENCIA IS NOT NULL AND MUNICIPIO_NOTIFICACION<>'-' 
--VALIDACIONES NACIONALIDAD
AND PAIS_EXPEDICION IS NOT NULL AND PAIS_NACIMIENTO IS NOT NULL AND PAIS_NACIONALIDAD IS NOT NULL 
--VALIDACIONES FECHAS
AND CLNAT_FECHA_NACIMIENTO BETWEEN TO_DATE('1900-01-01','YYYY-MM-DD') AND SYSDATE
)
'''