saldo_fondo='''SELECT SUM(ACDI_SALDO) FROM SF_TACDI WHERE ACDI_FECCIE=TO_DATE('{0}','YYYY-MM-DD') AND ACDI_FOND='{1}'
'''
query='''SELECT  DECODE(FDEI_TPID,'R','11','P','41','C','13','T','12', 'E','22','D','47','O','47','13') as TPIDENTIF,
        PTPL_FDEI as NRO_IDENTIF,ROUND(SUM(NVL(ACDI_SALDO,0))*100/{0},5) PORCENTAJE_SALDO ,TO_CHAR(MAX(PTPL_FECCRE),'YYYY-MM-DD') MAX_FECCRE FROM SF_TPTPL  
        INNER JOIN SF_TPLAN  ON PLAN_PLAN=PTPL_PLAN 
        INNER JOIN SF_TFDEI ON FDEI_FDEI=PTPL_FDEI
        LEFT JOIN (SELECT * FROM SF_TACDI
                        WHERE ACDI_FECCIE=TO_DATE('{1}','YYYY-MM-DD') AND ACDI_FOND='{2}') ON ACDI_PLAN=PLAN_PLAN
            WHERE PTPL_FOND='{2}' AND 
            TRUNC(PTPL_FECCRE)<=TRUNC(TO_DATE('{1}','YYYY-MM-DD')) AND 
            (TRUNC(PLAN_FECCAN) > TRUNC(TO_DATE('{1}', 'YYYY-MM-DD')) OR PLAN_FECCAN IS NULL) AND
            FDEI_TPID NOT IN ('A','F','X','N')
            GROUP BY PTPL_FDEI,FDEI_TPID
'''
cancelaciones_rendir='''SELECT DECODE(FDEI_TPID,'R','11','P','41','C','13','T','12', 'E','22','D','47','O','47','13') as TPIDENTIF,
PTPL_FDEI NRO_IDENTIF,TO_CHAR(FECCAN,'YYYY-MM-DD') FECCAN FROM (
SELECT PTPL_FDEI,FDEI_TPID, MAX(PLAN_FECCAN) FECCAN,SUM(ESTADO)  FROM (
SELECT PP.PTPL_FDEI,FDEI_TPID,PP.PTPL_PLAN,P.PLAN_FECING,P.PLAN_FECCAN,P.PLAN_ESTACT,CASE WHEN P.PLAN_ESTACT='CAN' AND PLAN_FECCAN<=TO_DATE('{0}','YYYY-MM-DD')
THEN 0 ELSE 1 END ESTADO FROM SF_TPTPL PP INNER JOIN SF_TPLAN P ON PTPL_PLAN=PLAN_PLAN 
INNER JOIN SF_TFDEI FD ON FDEI_FDEI=PP.PTPL_FDEI
WHERE PLAN_FOND='14' AND PLAN_FECING<=TO_DATE('{0}','YYYY-MM-DD') 
)
GROUP BY PTPL_FDEI,FDEI_TPID
HAVING SUM(ESTADO)=0
)
'''
cancelaciones_rentafacil='''SELECT DECODE(FDEI_TPID,'R','11','P','41','C','13','T','12', 'E','22','D','47','O','47','13') as TPIDENTIF,
PTPL_FDEI NRO_IDENTIF,TO_CHAR(FECCAN,'YYYY-MM-DD')  FECCAN FROM (
SELECT PTPL_FDEI,FDEI_TPID,MAX(NVL(PTPL_FECMOD,PLAN_FECCAN)) FECCAN,SUM(ESTADO) FROM (
SELECT PTPL_FDEI,FDEI_TPID,PTPL_FECMOD,PLAN_FECCAN,CASE WHEN PLAN_ESTACT='CAN' THEN 0 ELSE 1 END ESTADO FROM SF_TPTPL INNER JOIN SF_TPLAN ON PLAN_PLAN=PTPL_PLAN INNER JOIN SF_TFDEI ON FDEI_FDEI=PTPL_FDEI
where PTPL_FOND='12' AND PTPL_TIPO='T' AND FDEI_TPID NOT IN ('A','F','X','N') AND PLAN_FECING<=TO_DATE('{0}','YYYY-MM-DD')
)
GROUP BY PTPL_FDEI,FDEI_TPID
HAVING SUM(ESTADO)=0
) WHERE FECCAN<=TO_DATE('{0}','YYYY-MM-DD')
ORDER BY 3 DESC
'''
cancelaciones_universitas='''SELECT DECODE(FDEI_TPID,'R','11','P','41','C','13','T','12', 'E','22','D','47','O','47','13') as TPIDENTIF,
PTPL_FDEI NRO_IDENTIF,TO_CHAR(FECCAN,'YYYY-MM-DD') FECCAN FROM (
SELECT PTPL_FDEI,FDEI_TPID,MAX(NVL(PTPL_FECMOD,PLAN_FECCAN)) FECCAN,SUM(ESTADO) FROM (
SELECT PTPL_FDEI,FDEI_TPID,PTPL_FECMOD,PLAN_FECCAN,CASE WHEN PLAN_ESTACT='CAN' THEN 0 ELSE 1 END ESTADO FROM SF_TPTPL INNER JOIN SF_TPLAN ON PLAN_PLAN=PTPL_PLAN INNER JOIN SF_TFDEI ON FDEI_FDEI=PTPL_FDEI
where PTPL_FOND='10' AND PTPL_TIPO='T' AND FDEI_TPID NOT IN ('A','F','X','N') AND PLAN_FECING<=TO_DATE('{0}','YYYY-MM-DD')
)
GROUP BY PTPL_FDEI,FDEI_TPID
HAVING SUM(ESTADO)=0
) WHERE FECCAN<=TO_DATE('{0}','YYYY-MM-DD')
ORDER BY 3 DESC
'''
cancelaciones_cambio_tpidentif='''SELECT A.CLNTE_NROIDENT NRO_IDENTIF,TO_CHAR(MAX(A.CLNTE_FECCRE) ,'YYYY-MM-DD') FECCAN FROM CL_TCLNTE A INNER JOIN (
SELECT CLNTE_NROIDENT,COUNT(*) FROM CL_TCLNTE
WHERE CLNTE_FECCRE<=TO_DATE('{0}','YYYY-MM-DD') 
HAVING COUNT(*)>1
GROUP BY CLNTE_NROIDENT) B ON A.CLNTE_NROIDENT=B.CLNTE_NROIDENT
GROUP BY A.CLNTE_NROIDENT 
ORDER BY 2 DESC
'''
cancelaciones_cortoplazo='''SELECT PTPL_FDEI NRO_IDENTIF,FECCAN FROM (
SELECT PTPL_FDEI,MAX(NVL(PTPL_FECMOD,PLAN_FECCAN)) FECCAN,SUM(ESTADO) FROM (
SELECT PTPL_FDEI,PTPL_FECMOD,PLAN_FECCAN,CASE WHEN ptpl_status='I' THEN 0 ELSE 1 END ESTADO FROM SF_TPTPL INNER JOIN SF_TPLAN ON PLAN_PLAN=PTPL_PLAN INNER JOIN SF_TFDEI ON FDEI_FDEI=PTPL_FDEI
where PTPL_FOND='16' AND PTPL_TIPO='T' AND FDEI_TPID NOT IN ('A','F') AND PLAN_FECING<=TO_DATE('{0}','YYYY-MM-DD')
)
GROUP BY PTPL_FDEI
HAVING SUM(ESTADO)=0
) WHERE FECCAN<=TO_DATE('{0}','YYYY-MM-DD')
ORDER BY 2 DESC;
'''
cancelaciones_retiro="""SELECT PTPL_FDEI NRO_IDENTIF,FECCAN FROM (
SELECT PTPL_FDEI,MAX(NVL(PTPL_FECMOD,PLAN_FECCAN)) FECCAN,SUM(ESTADO) FROM (
SELECT PTPL_FDEI,PTPL_FECMOD,PLAN_FECCAN,CASE WHEN ptpl_status='I' THEN 0 ELSE 1 END ESTADO FROM SF_TPTPL INNER JOIN SF_TPLAN ON PLAN_PLAN=PTPL_PLAN INNER JOIN SF_TFDEI ON FDEI_FDEI=PTPL_FDEI
where PTPL_FOND='18' AND PTPL_TIPO='T' AND FDEI_TPID NOT IN ('A','F') AND PLAN_FECING<=TO_DATE('{0}','YYYY-MM-DD')
)
GROUP BY PTPL_FDEI
HAVING SUM(ESTADO)=0
) WHERE FECCAN<=TO_DATE('{0}','YYYY-MM-DD')
ORDER BY 2 DESC;
"""

