saldo_fondo='''SELECT SUM(ACDI_SALDO) FROM SF_TACDI WHERE ACDI_FECCIE=TO_DATE('{0}','YYYY-MM-DD') AND ACDI_FOND='{1}'
'''
query='''SELECT  PTPL_FDEI as NRO_IDENTIF,ROUND(SUM(NVL(ACDI_SALDO,0))*100/{0},5) PORCENTAJE_SALDO ,MAX(PTPL_FECCRE) MAX_FECCRE FROM SF_TPTPL  
        INNER JOIN SF_TPLAN  ON PLAN_PLAN=PTPL_PLAN 
        INNER JOIN SF_TFDEI ON FDEI_FDEI=PTPL_FDEI
        LEFT JOIN (SELECT * FROM SF_TACDI
                        WHERE ACDI_FECCIE=TO_DATE('{1}','YYYY-MM-DD') AND ACDI_FOND='{2}') ON ACDI_PLAN=PLAN_PLAN
            WHERE PTPL_FOND='{2}' AND 
            TRUNC(PTPL_FECCRE)<=TRUNC(TO_DATE('{1}','YYYY-MM-DD')) AND 
            (TRUNC(PLAN_FECCAN) > TRUNC(TO_DATE('{1}', 'YYYY-MM-DD')) OR PLAN_FECCAN IS NULL) AND
            FDEI_TPID NOT IN ('A','F')
            GROUP BY PTPL_FDEI
'''