# Generated by Django 4.2.7 on 2024-05-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDePersona',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('tipoPersona', models.CharField(db_column='tipo_persona', max_length=3)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
            ],
            options={
                'db_table': 'params_tipo_persona',
            },
        ),
        migrations.CreateModel(
            name='TipoDeDocumento',
            fields=[
                ('tipoDocumento', models.CharField(db_column='tipo_documento', max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
                ('idTipoPersona', models.ForeignKey(db_column='id_tipo_persona', on_delete=django.db.models.deletion.CASCADE, to='public.tipodepersona')),
            ],
            options={
                'db_table': 'params_tipo_documento',
            },
        ),
    ]
