# Generated by Django 4.2.7 on 2024-05-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoNovedadRPBF",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "params_tipo_novedad_rpbf",
            },
        ),
    ]
