# Generated by Django 4.2.7 on 2024-06-05 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0002_parametrosrpbf"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoParametrizacion",
            fields=[
                (
                    "acronimo",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Acronimo de el tipo de parametrizacion",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
            options={
                "db_table": "PARAMS_TIPO_PARAMETRIZACION",
            },
        ),
        migrations.CreateModel(
            name="ParametrosGenericos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "valorParametro",
                    models.TextField(
                        db_column="valor_parametro", verbose_name="Mensaje del log"
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "tipoParametrizacion",
                    models.ForeignKey(
                        db_column="tipo_parametrizacion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="public.tipoparametrizacion",
                        verbose_name="Tipo de parametrizacion general",
                    ),
                ),
            ],
            options={
                "db_table": "PARAMS_GENERIC_PARAM",
            },
        ),
    ]
