# Generated by Django 4.2.7 on 2024-06-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0002_priodotrimestral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametrosgenericos",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
