# Generated by Django 4.2.7 on 2024-07-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0003_alter_parametrosgenericos_nombre"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomologacionesRPBF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valorDian", models.CharField(db_column="valor_dian", max_length=4)),
                ("valorSgc", models.CharField(db_column="valor_sgc", max_length=4)),
                ("valorSifi", models.CharField(db_column="valor_sifi", max_length=4)),
            ],
            options={
                "db_table": "params_homologaciones_rpbf",
            },
        ),
    ]
