# Generated by Django 4.2.7 on 2024-05-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeProcesoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de proceso general')),
                ('descripcion', models.TextField(verbose_name='Descripcion del proceso tipo de proceso general')),
            ],
            options={
                'db_table': 'PRCS_TIPO_PROCESO_GENERAL',
            },
        ),
    ]
