# Generated by Django 4.2.7 on 2024-06-05 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisparadorEjecucion",
            fields=[
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de disparador de ejecucion"
                    ),
                ),
                (
                    "acronimo",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Acronimo de disparador de ejecucion",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        verbose_name="Descripcion del disparador de ejecucion"
                    ),
                ),
            ],
            options={
                "db_table": "PRCS_DISPARADOR_EJECUCION",
            },
        ),
        migrations.CreateModel(
            name="EjecucionProceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "celeryTaskId",
                    models.CharField(
                        db_column="celery_task_id",
                        max_length=100,
                        verbose_name="Id de la tarea de celery que ejecuta este proceso",
                    ),
                ),
                (
                    "fechaInicio",
                    models.DateTimeField(
                        db_column="fecha_inicio",
                        verbose_name="Fecha de inicio de la ejecución",
                    ),
                ),
                (
                    "fechaFin",
                    models.DateTimeField(
                        db_column="fecha_fin",
                        null=True,
                        verbose_name="Fecha de fin de la ejecución",
                    ),
                ),
                (
                    "resultado",
                    models.TextField(
                        verbose_name="Resultado de la ejecución del proceso"
                    ),
                ),
                (
                    "disparador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.disparadorejecucion",
                        verbose_name="Disparador de la ejecución de este proceso",
                    ),
                ),
            ],
            options={
                "db_table": "PRCS_EJECUCION_PROCESO",
            },
        ),
        migrations.CreateModel(
            name="EstadoEjecucion",
            fields=[
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de estado de ejecucion"
                    ),
                ),
                (
                    "acronimio",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Acronimo de estado de ejecucion",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        verbose_name="Descripcion del estado de ejecucion"
                    ),
                ),
            ],
            options={
                "db_table": "PRCS_ESTADO_EJECUCION",
            },
        ),
        migrations.CreateModel(
            name="TareaProceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre de tarea"),
                ),
                (
                    "acronimo",
                    models.CharField(max_length=50, verbose_name="Acronimo de tarea"),
                ),
                (
                    "funcionRelacionada",
                    models.CharField(
                        db_column="funcion_relacionada",
                        max_length=100,
                        verbose_name="Funcion en el codigo que tiene el decorador de tarea",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripcion general de la tarea"),
                ),
            ],
            options={
                "db_table": "PRCS_TAREA",
            },
        ),
        migrations.CreateModel(
            name="TipoDeProcesoGeneral",
            fields=[
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de proceso general"
                    ),
                ),
                (
                    "acronimo",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Acronimo de proceso general",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        verbose_name="Descripcion del proceso tipo de proceso general"
                    ),
                ),
            ],
            options={
                "db_table": "PRCS_TIPO_PROCESO_GENERAL",
            },
        ),
        migrations.CreateModel(
            name="TipoLog",
            fields=[
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de tipo de log"
                    ),
                ),
                (
                    "acronimo",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Acronimo de tipo de log",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripcion del tipo de log"),
                ),
            ],
            options={
                "db_table": "PRCS_TIPO_LOG",
            },
        ),
        migrations.CreateModel(
            name="Proceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre de proceso"),
                ),
                (
                    "acronimo",
                    models.CharField(max_length=50, verbose_name="Acronimo de proceso"),
                ),
                (
                    "funcionRelacionada",
                    models.CharField(
                        db_column="funcion_relacionada",
                        max_length=100,
                        verbose_name="Funcion en el codigo que tiene el decorador de proceso",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripcion general del proceso"),
                ),
                (
                    "stakeholders",
                    models.CharField(
                        max_length=100,
                        verbose_name="Stakeholder involucrados del proceso",
                    ),
                ),
                (
                    "modulosInvolucrados",
                    models.CharField(
                        db_column="modulos_involucrados",
                        max_length=100,
                        verbose_name="Modulos de datos que seran necesarios para ejecutar el proceso",
                    ),
                ),
                (
                    "tipoProceso",
                    models.ForeignKey(
                        db_column="tipo_proceso",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.tipodeprocesogeneral",
                        verbose_name="Tipo de Proceso general en el que encaja este proceso",
                    ),
                ),
            ],
            options={
                "db_table": "PRCS_PROCESO",
            },
        ),
        migrations.CreateModel(
            name="LogEjecucionTareaProceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensaje", models.TextField(verbose_name="Mensaje del log")),
                (
                    "ordenVisualizacion",
                    models.IntegerField(
                        db_column="orden_visualizacion",
                        verbose_name="Orden de visualizacion del log",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del log"
                    ),
                ),
                (
                    "ejecucionProceso",
                    models.ForeignKey(
                        db_column="ejecucion_proceso",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.ejecucionproceso",
                        verbose_name="Ejecucion de proceso asociada a este log",
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.tareaproceso",
                        verbose_name="Tarea asociada a este log",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.tipolog",
                        verbose_name="Tipo de log",
                    ),
                ),
            ],
            options={
                "db_table": "PRCS_LOG_EJECUCION_TAREA_PROCESO",
            },
        ),
        migrations.CreateModel(
            name="LogEjecucionProceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensaje", models.TextField(verbose_name="Mensaje del log")),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del log"
                    ),
                ),
                (
                    "ordenVisualizacion",
                    models.IntegerField(
                        db_column="orden_visualizacion",
                        verbose_name="Orden de visualizacion del log",
                    ),
                ),
                (
                    "ejecucionProceso",
                    models.ForeignKey(
                        db_column="ejecucion_proceso",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.ejecucionproceso",
                        verbose_name="Ejecucion de proceso asociada a este log",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.tipolog",
                        verbose_name="Tipo de log",
                    ),
                ),
            ],
            options={
                "db_table": "PRCS_LOG_EJECUCION_PROCESO",
            },
        ),
        migrations.AddField(
            model_name="ejecucionproceso",
            name="estadoEjecucion",
            field=models.ForeignKey(
                db_column="estado_ejecucion",
                on_delete=django.db.models.deletion.CASCADE,
                to="process.estadoejecucion",
                verbose_name="Estado de la ejecución de este proceso",
            ),
        ),
        migrations.AddField(
            model_name="ejecucionproceso",
            name="proceso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="process.proceso",
                verbose_name="Proceso asociado a esta ejecucion",
            ),
        ),
        migrations.AddField(
            model_name="ejecucionproceso",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que ejecuto el proceso",
            ),
        ),
        migrations.CreateModel(
            name="ProcesoTareaMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.IntegerField(null=True)),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.proceso",
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process.tareaproceso",
                    ),
                ),
            ],
            options={
                "db_table": "PRCS_PROCESO_TAREA_MAPA",
                "unique_together": {("proceso", "tarea")},
            },
        ),
    ]
