# Generated by Django 4.2.7 on 2024-05-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodeprocesogeneral',
            name='acronimo',
            field=models.CharField(default=0, max_length=10, verbose_name='Acronimo de proceso general'),
            preserve_default=False,
        ),
    ]
