# Generated by Django 4.2.7 on 2024-05-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='acronimo',
            field=models.CharField(max_length=50, verbose_name='Acronimo de proceso'),
        ),
        migrations.AlterField(
            model_name='tareaproceso',
            name='acronimo',
            field=models.CharField(max_length=50, verbose_name='Acronimo de tarea'),
        ),
    ]
