# Generated by Django 4.2.7 on 2024-05-07 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_tipodeprocesogeneral_acronimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de proceso')),
                ('acronimo', models.CharField(max_length=15, verbose_name='Acronimo de proceso')),
                ('descripcion', models.TextField(verbose_name='Descripcion general del proceso')),
                ('stakeholders', models.CharField(max_length=100, verbose_name='Stakeholder involucrados del proceso')),
                ('modulosInvolucrados', models.CharField(db_column='modulos_involucrados', max_length=100, verbose_name='Modulos de datos que seran necesarios para ejecutar el proceso')),
                ('tipoProceso', models.ForeignKey(db_column='tipo_proceso', on_delete=django.db.models.deletion.CASCADE, to='process.tipodeprocesogeneral', verbose_name='Tipo de Proceso general en el que encaja este proceso')),
            ],
            options={
                'db_table': 'PRCS_PROCESO',
            },
        ),
    ]
