# Generated by Django 4.2.7 on 2024-05-15 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_alter_proceso_acronimo_alter_tareaproceso_acronimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoTareaMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(null=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.proceso')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.tareaproceso')),
            ],
            options={
                'db_table': 'PRCS_PROCESO_TAREA_MAPA',
                'unique_together': {('proceso', 'tarea')},
            },
        ),
    ]
