# Generated by Django 4.2.7 on 2024-05-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_proceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='funcionRelacionada',
            field=models.CharField(default=0, max_length=100, verbose_name='Funcion en el codigo que tiene el decorador de proceso'),
            preserve_default=False,
        ),
    ]
