# Generated by Django 4.2.7 on 2024-05-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_proceso_funcionrelacionada'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de estado de ejecucion')),
                ('acronimio', models.CharField(max_length=10, verbose_name='Acronimo de estado de ejecucion')),
                ('descripcion', models.TextField(verbose_name='Descripcion del estado de ejecucion')),
            ],
            options={
                'db_table': 'PRCS_ESTADO_EJECUCION',
            },
        ),
    ]
