# Generated by Django 4.2.7 on 2024-05-07 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_estadoejecucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisparadorEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de disparador de ejecucion')),
                ('acronimo', models.CharField(max_length=10, verbose_name='Acronimo de disparador de ejecucion')),
                ('descripcion', models.TextField(verbose_name='Descripcion del disparador de ejecucion')),
            ],
            options={
                'db_table': 'PRCS_DISPARADOR_EJECUCION',
            },
        ),
        migrations.CreateModel(
            name='EjecucionProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField(verbose_name='Fecha de inicio de la ejecución')),
                ('fechaFin', models.DateTimeField(null=True, verbose_name='Fecha de fin de la ejecución')),
                ('resultado', models.TextField(verbose_name='Resultado de la ejecución del proceso')),
                ('disparador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.disparadorejecucion', verbose_name='Disparador de la ejecución de este proceso')),
                ('estadoEjecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.estadoejecucion', verbose_name='Estado de la ejecución de este proceso')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.proceso', verbose_name='Proceso asociado a esta ejecucion')),
            ],
            options={
                'db_table': 'PRCS_EJECUCION_PROCESO',
            },
        ),
    ]
