# Generated by Django 4.2.7 on 2024-05-07 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('process', '0006_disparadorejecucion_ejecucionproceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucionproceso',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que ejecuto el proceso'),
        ),
        migrations.AlterField(
            model_name='ejecucionproceso',
            name='estadoEjecucion',
            field=models.ForeignKey(db_column='estado_ejecucion', on_delete=django.db.models.deletion.CASCADE, to='process.estadoejecucion', verbose_name='Estado de la ejecución de este proceso'),
        ),
        migrations.AlterField(
            model_name='ejecucionproceso',
            name='fechaFin',
            field=models.DateTimeField(db_column='fecha_fin', null=True, verbose_name='Fecha de fin de la ejecución'),
        ),
        migrations.AlterField(
            model_name='ejecucionproceso',
            name='fechaInicio',
            field=models.DateTimeField(db_column='fecha_inicio', verbose_name='Fecha de inicio de la ejecución'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='funcionRelacionada',
            field=models.CharField(db_column='funcion_relacionada', max_length=100, verbose_name='Funcion en el codigo que tiene el decorador de proceso'),
        ),
    ]
