# Generated by Django 4.2.7 on 2023-12-12 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDePersona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoPersona', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeDocumento',
            fields=[
                ('TipoDocumento', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
                ('idTipoPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidecomisos.tipodepersona')),
            ],
        ),
        migrations.CreateModel(
            name='Fideicomiso',
            fields=[
                ('CodigoSFC', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('FechaCreacion', models.DateField()),
                ('FechaVencimiento', models.DateField()),
                ('FechaProrroga', models.DateField()),
                ('Estado', models.CharField(max_length=1)),
                ('TipoIdentificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidecomisos.tipodedocumento')),
            ],
        ),
        migrations.CreateModel(
            name='EncargoTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroEncargo', models.CharField(max_length=50)),
                ('NumeroProducto', models.CharField(max_length=50)),
                ('Fideicomiso', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=300)),
            ],
            options={
                'unique_together': {('NumeroEncargo', 'Fideicomiso')},
            },
        ),
        migrations.CreateModel(
            name='Encargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroEncargo', models.CharField(max_length=50)),
                ('NumeroProducto', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Fideicomiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargos', to='fidecomisos.fideicomiso')),
            ],
            options={
                'unique_together': {('NumeroEncargo', 'Fideicomiso')},
            },
        ),
    ]
