# Generated by Django 4.2.7 on 2023-12-04 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDePersona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoPersona', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeDocumento',
            fields=[
                ('TipoDocumento', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=20)),
                ('idTipoPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidecomisos.tipodepersona')),
            ],
        ),
        migrations.CreateModel(
            name='Fideicomiso',
            fields=[
                ('CodigoSFC', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=60)),
                ('FechaCreacion', models.DateField()),
                ('FechaVencimiento', models.DateField()),
                ('FechaProrroga', models.DateField()),
                ('TipoIdentificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidecomisos.tipodedocumento')),
            ],
        ),
    ]
