# Generated by Django 4.2.7 on 2024-05-08 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fideicomiso',
            fields=[
                ('codigoSFC', models.IntegerField(db_column='codigo_sfc', db_index=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('fechaCreacion', models.DateField(db_column='fecha_creacion')),
                ('fechaVencimiento', models.DateField(db_column='fecha_vencimiento')),
                ('fechaProrroga', models.DateField(db_column='fecha_prorroga')),
                ('estado', models.CharField(db_column='estado', max_length=1)),
                ('tipoIdentificacion', models.ForeignKey(db_column='tipo_identificacion', on_delete=django.db.models.deletion.CASCADE, to='public.tipodedocumento')),
            ],
            options={
                'db_table': 'fidei_fideicomiso',
            },
        ),
        migrations.CreateModel(
            name='EncargoTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroEncargo', models.CharField(db_column='numero_encargo', max_length=50)),
                ('fideicomiso', models.CharField(db_column='fideicomiso', max_length=50)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=300)),
            ],
            options={
                'unique_together': {('numeroEncargo', 'fideicomiso')},
            },
        ),
        migrations.CreateModel(
            name='Encargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroEncargo', models.CharField(db_column='numero_encargo', max_length=50)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=300, null=True)),
                ('fideicomiso', models.ForeignKey(db_column='fideicomiso', on_delete=django.db.models.deletion.CASCADE, related_name='encargos', to='fidecomisos.fideicomiso')),
            ],
            options={
                'db_table': 'encargo',
                'unique_together': {('numeroEncargo', 'fideicomiso')},
            },
        ),
    ]
