# Generated by Django 4.2.7 on 2024-05-01 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fidecomisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fideicomiso',
            table='fidei_fideicomiso',
        ),
    ]
