# Generated by Django 4.2.7 on 2023-12-07 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fidecomisos', '0003_fideicomiso_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroEncargo', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=100)),
                ('Fideicomiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargos', to='fidecomisos.fideicomiso')),
            ],
        ),
    ]
