# Generated by Django 4.2.7 on 2024-05-02 00:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logs_transactions', '0001_initial_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_cambios_create',
            name='signalId',
            field=models.CharField(db_column='signal_id', default=uuid.uuid4, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='log_cambios_delete',
            name='signalId',
            field=models.CharField(db_column='signal_id', default=uuid.uuid4, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='log_cambios_m2m',
            name='signalId',
            field=models.CharField(db_column='signal_id', default=uuid.uuid4, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='log_cambios_update',
            name='signalId',
            field=models.CharField(db_column='signal_id', default=uuid.uuid4, max_length=36, null=True),
        ),
    ]
