# Generated by Django 5.0.6 on 2024-06-07 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs_transactions", "0001_initial"),
        ("process", "0003_procesotareamap"),
    ]

    operations = [
        migrations.AddField(
            model_name="log_cambios_create",
            name="tipoProceso",
            field=models.ForeignKey(
                db_column="tipo_proceso",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process.tipodeprocesogeneral",
            ),
        ),
        migrations.AddField(
            model_name="log_cambios_delete",
            name="tipoProceso",
            field=models.ForeignKey(
                db_column="tipo_proceso",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process.tipodeprocesogeneral",
            ),
        ),
        migrations.AddField(
            model_name="log_cambios_m2m",
            name="tipoProceso",
            field=models.ForeignKey(
                db_column="tipo_proceso",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process.tipodeprocesogeneral",
            ),
        ),
        migrations.AddField(
            model_name="log_cambios_update",
            name="tipoProceso",
            field=models.ForeignKey(
                db_column="tipo_proceso",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process.tipodeprocesogeneral",
            ),
        ),
    ]
