# Generated by Django 4.2.7 on 2024-05-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs_transactions', '0002_log_cambios_create_signalid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_cambios_delete',
            name='objectId',
            field=models.CharField(db_column='object_id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='log_cambios_m2m',
            name='objectId',
            field=models.CharField(db_column='object_id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='log_cambios_update',
            name='objectId',
            field=models.CharField(db_column='object_id', max_length=255, null=True),
        ),
    ]
