# Generated by Django 5.0.6 on 2024-06-07 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs_transactions", "0002_log_cambios_create_tipoproceso_and_more"),
        ("process", "0003_procesotareamap"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log_cambios_create",
            name="tipoProceso",
        ),
        migrations.RemoveField(
            model_name="log_cambios_delete",
            name="tipoProceso",
        ),
        migrations.RemoveField(
            model_name="log_cambios_m2m",
            name="tipoProceso",
        ),
        migrations.RemoveField(
            model_name="log_cambios_update",
            name="tipoProceso",
        ),
        migrations.AddField(
            model_name="log_cambios_create",
            name="tipoProcesoEjecucion",
            field=models.ForeignKey(
                db_column="tipo_proceso_ejecucion",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process.disparadorejecucion",
            ),
        ),
        migrations.AddField(
            model_name="log_cambios_delete",
            name="tipoProcesoEjecucion",
            field=models.ForeignKey(
                db_column="tipo_proceso_ejecucion",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process.disparadorejecucion",
            ),
        ),
        migrations.AddField(
            model_name="log_cambios_m2m",
            name="tipoProcesoEjecucion",
            field=models.ForeignKey(
                db_column="tipo_proceso_ejecucion",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process.disparadorejecucion",
            ),
        ),
        migrations.AddField(
            model_name="log_cambios_update",
            name="tipoProcesoEjecucion",
            field=models.ForeignKey(
                db_column="tipo_proceso_ejecucion",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process.disparadorejecucion",
            ),
        ),
    ]
