# Generated by Django 4.2.7 on 2024-05-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs_transactions', '0003_alter_log_cambios_delete_objectid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_cambios_create',
            name='objectId',
            field=models.CharField(db_column='object_id', max_length=255, null=True),
        ),
    ]
