# Generated by Django 5.0.6 on 2024-06-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs_transactions", "0003_remove_log_cambios_create_tipoproceso_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log_cambios_create",
            name="objectId",
            field=models.CharField(
                db_column="object_id", max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="log_cambios_delete",
            name="objectId",
            field=models.CharField(
                db_column="object_id", max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="log_cambios_m2m",
            name="objectId",
            field=models.CharField(
                db_column="object_id", max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="log_cambios_update",
            name="objectId",
            field=models.CharField(
                db_column="object_id", max_length=255, null=True, unique=True
            ),
        ),
    ]
