# Generated by Django 4.2.7 on 2024-05-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs_transactions', '0004_alter_log_cambios_create_objectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_cambios_m2m',
            name='objectIdPadre',
            field=models.CharField(db_column='object_id_padre', max_length=255, null=True),
        ),
    ]
