# Generated by Django 4.2.7 on 2024-04-23 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Cambios_Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ip', models.GenericIPAddressField()),
                ('TiempoAccion', models.DateTimeField(auto_now_add=True)),
                ('NombreModelo', models.CharField(max_length=50)),
                ('NombreCampo', models.CharField(max_length=50)),
                ('AntiguoValor', models.TextField(null=True)),
                ('NuevoValor', models.TextField(null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=36, null=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Log_Cambios_Delete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ip', models.GenericIPAddressField()),
                ('TiempoAccion', models.DateTimeField(auto_now_add=True)),
                ('NombreModelo', models.CharField(max_length=50)),
                ('NombreCampo', models.CharField(max_length=255)),
                ('AntiguoValor', models.TextField(null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=36, null=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Log_Cambios_Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ip', models.GenericIPAddressField()),
                ('TiempoAccion', models.DateTimeField(auto_now_add=True)),
                ('NombreModelo', models.CharField(max_length=50)),
                ('NombreCampo', models.CharField(max_length=50)),
                ('NuevoValor', models.TextField(null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=36, null=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
