# Generated by Django 4.2.7 on 2023-12-28 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Cambios_Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ip', models.GenericIPAddressField()),
                ('Tiempo_Accion', models.DateTimeField(auto_now_add=True)),
                ('Nombre_Modelo', models.CharField(max_length=50)),
                ('Nombre_Campo', models.CharField(max_length=50)),
                ('Antiguo_Valor', models.TextField(null=True)),
                ('Nuevo_Valor', models.TextField(null=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log_Cambios_Delete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ip', models.GenericIPAddressField()),
                ('Tiempo_Accion', models.DateTimeField(auto_now_add=True)),
                ('Nombre_Modelo', models.CharField(max_length=50)),
                ('Antiguo_Valor', models.TextField(null=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log_Cambios_Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ip', models.GenericIPAddressField()),
                ('Tiempo_Accion', models.DateTimeField(auto_now_add=True)),
                ('Nombre_Modelo', models.CharField(max_length=50)),
                ('Nombre_Campo', models.CharField(max_length=50)),
                ('Nuevo_Valor', models.TextField(null=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
