# Generated by Django 4.2.7 on 2024-01-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_Changes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_cambios_create',
            old_name='Nombre_Campo',
            new_name='NombreCampo',
        ),
        migrations.RenameField(
            model_name='log_cambios_create',
            old_name='Nombre_Modelo',
            new_name='NombreModelo',
        ),
        migrations.RenameField(
            model_name='log_cambios_create',
            old_name='Tiempo_Accion',
            new_name='TiempoAccion',
        ),
        migrations.RenameField(
            model_name='log_cambios_delete',
            old_name='Antiguo_Valor',
            new_name='AntiguoValor',
        ),
        migrations.RenameField(
            model_name='log_cambios_delete',
            old_name='Nombre_Modelo',
            new_name='NombreModelo',
        ),
        migrations.RenameField(
            model_name='log_cambios_delete',
            old_name='Tiempo_Accion',
            new_name='TiempoAccion',
        ),
        migrations.RenameField(
            model_name='log_cambios_update',
            old_name='Antiguo_Valor',
            new_name='AntiguoValor',
        ),
        migrations.RenameField(
            model_name='log_cambios_update',
            old_name='Nombre_Campo',
            new_name='NombreCampo',
        ),
        migrations.RenameField(
            model_name='log_cambios_update',
            old_name='Nombre_Modelo',
            new_name='NombreModelo',
        ),
        migrations.RenameField(
            model_name='log_cambios_update',
            old_name='Nuevo_Valor',
            new_name='NuevoValor',
        ),
        migrations.RenameField(
            model_name='log_cambios_update',
            old_name='Tiempo_Accion',
            new_name='TiempoAccion',
        ),
        migrations.RemoveField(
            model_name='log_cambios_create',
            name='Nuevo_Valor',
        ),
        migrations.AddField(
            model_name='log_cambios_create',
            name='NuevoValor',
            field=models.TextField(null=True),
        ),
    ]
