# Generated by Django 4.2.7 on 2024-04-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Log_Changes",
            "0002_rename_nombre_campo_log_cambios_create_nombrecampo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="log_cambios_delete",
            name="NombreCampo",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
