# Generated by Django 4.2.7 on 2024-04-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_Changes', '0002_log_cambios_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_cambios_m2m',
            name='JsonValue',
            field=models.TextField(null=True),
        ),
    ]
