# Generated by Django 4.2.7 on 2024-04-22 21:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("Log_Changes", "0004_log_cambios_create_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="log_cambios_create",
            name="request_id",
            field=models.CharField(default=uuid.uuid4, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="log_cambios_delete",
            name="request_id",
            field=models.CharField(default=uuid.uuid4, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="log_cambios_update",
            name="request_id",
            field=models.CharField(default=uuid.uuid4, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="log_cambios_create",
            name="content_type",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="log_cambios_create",
            name="object_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
