# Generated by Django 4.2.7 on 2023-12-12 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fidecomisos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActorDeContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoActor', models.CharField(max_length=90)),
                ('Descripcion', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='ActorDeContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroIdentificacion', models.CharField(max_length=12)),
                ('Nombre', models.CharField(max_length=100)),
                ('FechaActualizacion', models.DateField()),
                ('EncargoAsociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidecomisos.encargo')),
                ('FideicomisoAsociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidecomisos.fideicomiso')),
                ('TipoActor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actores_de_contrato_cargue.tipoactordecontrato')),
                ('TipoIdentificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidecomisos.tipodedocumento')),
            ],
        ),
        migrations.AddConstraint(
            model_name='actordecontrato',
            constraint=models.UniqueConstraint(fields=('NumeroIdentificacion', 'FideicomisoAsociado'), name='unique_identificacion_fideicomiso'),
        ),
    ]
