# Generated by Django 4.2.7 on 2023-12-04 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fidecomisos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActorDeContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoActor', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActorDeContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroIdentificacion', models.CharField(max_length=18)),
                ('Nombre', models.CharField(max_length=50)),
                ('FideicomisoAsociado', models.IntegerField()),
                ('FechaActualizacion', models.DateField()),
                ('TipoActor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actores_de_contrato_cargue.tipoactordecontrato')),
                ('TipoIdentificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidecomisos.tipodedocumento')),
            ],
        ),
    ]
