# Generated by Django 4.2.7 on 2023-12-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actores_de_contrato_cargue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actordecontrato',
            name='unique_identificacion_fideicomiso',
        ),
        migrations.AddConstraint(
            model_name='actordecontrato',
            constraint=models.UniqueConstraint(fields=('NumeroIdentificacion', 'FideicomisoAsociado', 'EncargoAsociado'), name='unique_identificacion_fideicomiso_encargo'),
        ),
    ]
