# Generated by Django 4.2.7 on 2023-12-07 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fidecomisos', '0002_alter_tipodedocumento_descripcion_and_more'),
        ('actores_de_contrato_cargue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actordecontrato',
            name='FideicomisoAsociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidecomisos.fideicomiso'),
        ),
    ]
