# Generated by Django 4.2.7 on 2023-12-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actores_de_contrato_cargue', '0002_alter_actordecontrato_fideicomisoasociado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actordecontrato',
            name='Nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='actordecontrato',
            name='NumeroIdentificacion',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='tipoactordecontrato',
            name='Descripcion',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='tipoactordecontrato',
            name='TipoActor',
            field=models.CharField(max_length=90),
        ),
    ]
