# Generated by Django 4.2.7 on 2023-12-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actores_de_contrato_cargue', '0002_remove_actordecontrato_unique_identificacion_fideicomiso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actordecontrato',
            old_name='Nombre',
            new_name='Primer_Nombre',
        ),
        migrations.AddField(
            model_name='actordecontrato',
            name='Primer_Apellido',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actordecontrato',
            name='Segundo_Apellido',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actordecontrato',
            name='Segundo_Nombre',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
