# Generated by Django 4.2.7 on 2023-12-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actores_de_contrato_cargue', '0003_alter_actordecontrato_nombre_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='actordecontrato',
            constraint=models.UniqueConstraint(fields=('NumeroIdentificacion', 'FideicomisoAsociado'), name='unique_identificacion_fideicomiso'),
        ),
    ]
