# Generated by Django 4.2.7 on 2023-12-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actores_de_contrato_cargue', '0004_actordecontrato_activo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actordecontrato',
            name='unique_identificacion_fideicomiso_encargo',
        ),
        migrations.RemoveField(
            model_name='actordecontrato',
            name='EncargoAsociado',
        ),
        migrations.AddConstraint(
            model_name='actordecontrato',
            constraint=models.UniqueConstraint(fields=('NumeroIdentificacion', 'FideicomisoAsociado'), name='unique_identificacion_fideicomiso'),
        ),
    ]
