# Generated by Django 4.2.7 on 2024-01-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidecomisos', '0002_remove_encargo_numeroproducto_and_more'),
        ('actores_de_contrato_cargue', '0005_remove_actordecontrato_unique_identificacion_fideicomiso_encargo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actordecontrato',
            name='unique_identificacion_fideicomiso',
        ),
        migrations.RemoveField(
            model_name='actordecontrato',
            name='FideicomisoAsociado',
        ),
        migrations.AddConstraint(
            model_name='actordecontrato',
            constraint=models.UniqueConstraint(fields=('NumeroIdentificacion',), name='unique_identificacion'),
        ),
        migrations.AddField(
            model_name='actordecontrato',
            name='FideicomisoAsociado',
            field=models.ManyToManyField(to='fidecomisos.fideicomiso'),
        ),
    ]
