# Generated by Django 4.2.7 on 2024-01-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actores_de_contrato_cargue', '0006_remove_actordecontrato_unique_identificacion_fideicomiso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actordecontrato',
            old_name='Primer_Apellido',
            new_name='PrimerApellido',
        ),
        migrations.RenameField(
            model_name='actordecontrato',
            old_name='Primer_Nombre',
            new_name='PrimerNombre',
        ),
        migrations.RenameField(
            model_name='actordecontrato',
            old_name='Segundo_Apellido',
            new_name='SegundoApellido',
        ),
        migrations.RenameField(
            model_name='actordecontrato',
            old_name='Segundo_Nombre',
            new_name='SegundoNombre',
        ),
    ]
