# Generated by Django 4.2.7 on 2024-04-18 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "actores_de_contrato_cargue",
            "0007_rename_primer_apellido_actordecontrato_primerapellido_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="actordecontrato",
            name="FechaCreacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
