# Generated by Django 4.2.7 on 2024-04-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actores_de_contrato_cargue', '0008_actordecontrato_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actordecontrato',
            name='FechaActualizacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='actordecontrato',
            name='FechaCreacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
