# Generated by Django 4.2.7 on 2024-04-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actores_de_contrato_cargue', '0009_alter_actordecontrato_fechaactualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actordecontrato',
            name='FechaActualizacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='actordecontrato',
            name='FechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
