# Generated by Django 4.2.7 on 2024-04-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "actores_de_contrato_cargue",
            "0010_alter_actordecontrato_fechaactualizacion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="actordecontrato",
            name="FechaActualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
