# Generated by Django 4.2.7 on 2024-04-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actores_de_contrato_cargue", "0011_alter_actordecontrato_fechaactualizacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actordecontrato",
            name="SegundoApellido",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="actordecontrato",
            name="SegundoNombre",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
