# Generated by Django 4.2.7 on 2024-04-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "actores_de_contrato_cargue",
            "0012_alter_actordecontrato_segundoapellido_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="actordecontrato",
            name="SegundoApellido",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="actordecontrato",
            name="SegundoNombre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
