# Generated by Django 4.2.7 on 2024-04-26 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fidecomisos", "0003_rename_description_tipodepersona_description_and_more"),
        (
            "actores_de_contrato_cargue",
            "0013_alter_actordecontrato_segundoapellido_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RelacionFideicomisoActor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="actordecontrato",
            name="unique_identificacion",
        ),
        migrations.RemoveField(
            model_name="actordecontrato",
            name="TipoActor",
        ),
        migrations.AddConstraint(
            model_name="actordecontrato",
            constraint=models.UniqueConstraint(
                fields=("TipoIdentificacion", "NumeroIdentificacion"),
                name="unique_identificacion",
            ),
        ),
        migrations.AddField(
            model_name="relacionfideicomisoactor",
            name="Actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="actores_de_contrato_cargue.actordecontrato",
            ),
        ),
        migrations.AddField(
            model_name="relacionfideicomisoactor",
            name="Fideicomiso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fidecomisos.fideicomiso",
            ),
        ),
        migrations.AddField(
            model_name="relacionfideicomisoactor",
            name="TipoActor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="actores_de_contrato_cargue.tipoactordecontrato",
            ),
        ),
        migrations.AlterField(
            model_name="actordecontrato",
            name="FideicomisoAsociado",
            field=models.ManyToManyField(
                through="actores_de_contrato_cargue.RelacionFideicomisoActor",
                to="fidecomisos.fideicomiso",
            ),
        ),
    ]
