# Generated by Django 4.2.7 on 2024-04-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actores_de_contrato_cargue", "0014_relacionfideicomisoactor_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="relacionfideicomisoactor",
            constraint=models.UniqueConstraint(
                fields=("Actor", "Fideicomiso"), name="unique_fideicomiso_actor"
            ),
        ),
    ]
