# Generated by Django 4.2.7 on 2024-06-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("public", "0001_initial"),
        ("fidecomisos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActorDeContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numeroIdentificacion",
                    models.CharField(db_column="numero_identificacion", max_length=12),
                ),
                (
                    "fechaCreacion",
                    models.DateTimeField(auto_now_add=True, db_column="fecha_creacion"),
                ),
                (
                    "fechaActualizacion",
                    models.DateTimeField(
                        auto_now=True, db_column="fecha_actualizacion"
                    ),
                ),
                (
                    "estado",
                    models.CharField(db_column="estado", default="ACT", max_length=100),
                ),
            ],
            options={
                "db_table": "fidei_actor",
            },
        ),
        migrations.CreateModel(
            name="TipoActorDeContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipoActor", models.CharField(db_column="tipo_actor", max_length=90)),
                (
                    "descripcion",
                    models.CharField(db_column="descripcion", max_length=90),
                ),
            ],
            options={
                "db_table": "params_tipo_actor",
            },
        ),
        migrations.CreateModel(
            name="ActorDeContratoJuridico",
            fields=[
                (
                    "actordecontrato_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="actores.actordecontrato",
                    ),
                ),
                (
                    "razonSocialNombre",
                    models.CharField(db_column="razon_social", max_length=100),
                ),
            ],
            options={
                "db_table": "fidei_actor_jur",
            },
            bases=("actores.actordecontrato",),
        ),
        migrations.CreateModel(
            name="ActorDeContratoNatural",
            fields=[
                (
                    "actordecontrato_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="actores.actordecontrato",
                    ),
                ),
                (
                    "primerNombre",
                    models.CharField(db_column="primer_nombre", max_length=100),
                ),
                (
                    "segundoNombre",
                    models.CharField(
                        blank=True,
                        db_column="segundo_nombre",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "primerApellido",
                    models.CharField(db_column="primer_apellido", max_length=100),
                ),
                (
                    "segundoApellido",
                    models.CharField(
                        blank=True,
                        db_column="segundo_apellido",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "fidei_actor_nat",
            },
            bases=("actores.actordecontrato",),
        ),
        migrations.CreateModel(
            name="RelacionFideicomisoActor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        db_column="actor",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actores.actordecontrato",
                    ),
                ),
                (
                    "fideicomiso",
                    models.ForeignKey(
                        db_column="fideicomiso",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fidecomisos.fideicomiso",
                    ),
                ),
                ("tipoActor", models.ManyToManyField(to="actores.tipoactordecontrato")),
            ],
            options={
                "db_table": "fidei_actor_fideicomiso",
            },
        ),
        migrations.AddField(
            model_name="actordecontrato",
            name="fideicomisoAsociado",
            field=models.ManyToManyField(
                through="actores.RelacionFideicomisoActor", to="fidecomisos.fideicomiso"
            ),
        ),
        migrations.AddField(
            model_name="actordecontrato",
            name="tipoIdentificacion",
            field=models.ForeignKey(
                db_column="tipo_identificacion",
                on_delete=django.db.models.deletion.CASCADE,
                to="public.tipodedocumento",
            ),
        ),
        migrations.AddConstraint(
            model_name="relacionfideicomisoactor",
            constraint=models.UniqueConstraint(
                fields=("actor", "fideicomiso"), name="unique_fideicomiso_actor"
            ),
        ),
        migrations.AddConstraint(
            model_name="actordecontrato",
            constraint=models.UniqueConstraint(
                fields=("tipoIdentificacion", "numeroIdentificacion"),
                name="unique_identificacion",
            ),
        ),
    ]
