# Generated by Django 5.0.6 on 2024-07-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actores", "0001_initial"),
        ("fidecomisos", "0001_initial"),
        ("public", "0003_alter_parametrosgenericos_nombre"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuturoComprador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numeroIdentificacion",
                    models.CharField(
                        blank=True,
                        db_column="numero_identificacion",
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "fechaCreacion",
                    models.DateTimeField(auto_now_add=True, db_column="fecha_creacion"),
                ),
                (
                    "fechaActualizacion",
                    models.DateTimeField(
                        auto_now=True, db_column="fecha_actualizacion"
                    ),
                ),
                (
                    "estado",
                    models.CharField(db_column="estado", default="ACT", max_length=100),
                ),
                (
                    "tipoIdentificacion",
                    models.ForeignKey(
                        blank=True,
                        db_column="tipo_identificacion",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="public.tipodedocumento",
                    ),
                ),
            ],
            options={
                "db_table": "futuro_comprador",
            },
        ),
        migrations.CreateModel(
            name="RelacionFideicomisoFuturoComprador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FuturoComprador",
                    models.ForeignKey(
                        db_column="futuro_comprador",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actores.futurocomprador",
                    ),
                ),
                (
                    "fideicomiso",
                    models.ForeignKey(
                        db_column="fideicomiso",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fidecomisos.fideicomiso",
                    ),
                ),
                ("tipoActor", models.ManyToManyField(to="actores.tipoactordecontrato")),
            ],
            options={
                "db_table": "fidei_futuro_comprador_fideicomiso",
            },
        ),
        migrations.AddField(
            model_name="futurocomprador",
            name="fideicomisoAsociado",
            field=models.ManyToManyField(
                through="actores.RelacionFideicomisoFuturoComprador",
                to="fidecomisos.fideicomiso",
            ),
        ),
        migrations.AddConstraint(
            model_name="relacionfideicomisofuturocomprador",
            constraint=models.UniqueConstraint(
                fields=("FuturoComprador", "fideicomiso"),
                name="unique_fideicomiso_futuro_comprador",
            ),
        ),
    ]
