# Generated by Django 4.2.7 on 2024-05-10 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorDeContratoJuridico',
            fields=[
                ('actordecontrato_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actores.actordecontrato')),
                ('razonSocialNombre', models.CharField(db_column='razon_social', max_length=100)),
            ],
            options={
                'db_table': 'fidei_actor_jur',
            },
            bases=('actores.actordecontrato',),
        ),
        migrations.RemoveField(
            model_name='actordecontrato',
            name='primerApellido',
        ),
        migrations.RemoveField(
            model_name='actordecontrato',
            name='primerNombre',
        ),
        migrations.RemoveField(
            model_name='actordecontrato',
            name='segundoApellido',
        ),
        migrations.RemoveField(
            model_name='actordecontrato',
            name='segundoNombre',
        ),
        migrations.CreateModel(
            name='ActorDeContratoNatural',
            fields=[
                ('actordecontrato_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actores.actordecontrato')),
                ('primerNombre', models.CharField(db_column='primer_nombre', max_length=100)),
                ('segundoNombre', models.CharField(blank=True, db_column='segundo_nombre', max_length=100, null=True)),
                ('primerApellido', models.CharField(db_column='primer_apellido', max_length=100)),
                ('segundoApellido', models.CharField(blank=True, db_column='segundo_apellido', max_length=100, null=True)),
            ],
            options={
                'db_table': 'fidei_actor_nat',
            },
            bases=('actores.actordecontrato',),
        ),
    ]
