# Generated by Django 5.0.6 on 2024-07-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actores", "0002_futurocomprador_relacionfideicomisofuturocomprador_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relacionfideicomisofuturocomprador",
            name="tipoActor",
        ),
    ]
