# Generated by Django 4.2.7 on 2024-07-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actores", "0004_alter_futurocomprador_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="futurocomprador",
            name="primerApellido",
            field=models.CharField(
                db_column="primer_apellido", default=0, max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="futurocomprador",
            name="primerNombre",
            field=models.CharField(
                db_column="primer_nombre", default=0, max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="futurocomprador",
            name="razonSocialNombre",
            field=models.CharField(db_column="razon_social", default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="futurocomprador",
            name="segundoApellido",
            field=models.CharField(
                blank=True, db_column="segundo_apellido", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="futurocomprador",
            name="segundoNombre",
            field=models.CharField(
                blank=True, db_column="segundo_nombre", max_length=100, null=True
            ),
        ),
    ]
