# Generated by Django 4.2.7 on 2024-07-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actores", "0005_futurocomprador_primerapellido_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="relacionfideicomisofuturocomprador",
            old_name="FuturoComprador",
            new_name="futuroComprador",
        ),
    ]
