# Generated by Django 4.2.7 on 2024-07-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "actores",
            "0006_rename_futurocomprador_relacionfideicomisofuturocomprador_futurocomprador",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="relacionfideicomisofuturocomprador",
            name="unique_fideicomiso_futuro_comprador",
        ),
        migrations.AddConstraint(
            model_name="relacionfideicomisofuturocomprador",
            constraint=models.UniqueConstraint(
                fields=("futuroComprador", "fideicomiso"),
                name="unique_fideicomiso_futuro_comprador",
            ),
        ),
    ]
