# Generated by Django 4.2.7 on 2024-07-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actores", "0008_futurocomprador_tipopersona"),
    ]

    operations = [
        migrations.AlterField(
            model_name="futurocomprador",
            name="primerApellido",
            field=models.CharField(
                blank=True, db_column="primer_apellido", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="futurocomprador",
            name="primerNombre",
            field=models.CharField(
                blank=True, db_column="primer_nombre", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="futurocomprador",
            name="razonSocialNombre",
            field=models.CharField(
                blank=True, db_column="razon_social", max_length=100, null=True
            ),
        ),
    ]
