# Generated by Django 4.2.7 on 2023-11-27 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=12, unique=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ADMIN'), (2, 'AGENTE_CAT'), (3, 'AUDITORIA'), (4, 'AUXCUMP'), (5, 'AUXFIDU'), (6, 'AUXPRIESGO'), (7, 'AUXTES'), (8, 'COPERFIDU'), (9, 'CORCUMP'), (10, 'NEGFID'), (11, 'OPER'), (12, 'AGENTE_FIDECOMISOS'), (13, 'EMPLEADO')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
