# Generated by Django 4.2.7 on 2023-11-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='correo_empresarial',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(12, 'ADMIN'), (1, 'AGENTE_CAT'), (2, 'AUDITORIA'), (3, 'AUXCUMP'), (4, 'AUXFIDU'), (5, 'AUXPRIESGO'), (6, 'AUXTES'), (7, 'COPERFIDU'), (8, 'CORCUMP'), (9, 'NEGFID'), (10, 'OPER'), (11, 'AGENTE_FIDECOMISOS')], null=True),
        ),
    ]
