# Generated by Django 4.2.7 on 2024-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=10)),
            ],
        ),
        #migrations.RemoveConstraint(
        #    model_name="permisos",
        #    name="unique_rol_vista",
        #),
        migrations.AddConstraint(
            model_name="permisos",
            constraint=models.UniqueConstraint(
                fields=("rol", "vista"), name="unique_rol_vistaa"
            ),
        ),
    ]
