# Generated by Django 4.2.7 on 2024-01-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_taskschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskSchedule',
        ),
        migrations.RemoveConstraint(
            model_name='permisos',
            name='unique_role_view',
        ),
        migrations.RenameField(
            model_name='permisos',
            old_name='role',
            new_name='Rol',
        ),
        migrations.RenameField(
            model_name='permisos',
            old_name='view',
            new_name='Vista',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='cedula',
            new_name='Cedula',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='rol',
            new_name='Rol',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='Usuario',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='view',
            old_name='name',
            new_name='Nombre',
        ),
        migrations.AddConstraint(
            model_name='permisos',
            constraint=models.UniqueConstraint(fields=('Rol', 'Vista'), name='unique_rol_vista'),
        ),
    ]
