# Generated by Django 5.0.6 on 2024-06-11 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_pantalla"),
    ]

    operations = [
        migrations.AddField(
            model_name="permisos",
            name="pantalla",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.pantalla",
            ),
            preserve_default=False,
        ),
    ]
