# Generated by Django 4.2.7 on 2024-05-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_accion_remove_permisos_unique_rol_vista_and_more"),
    ]

    operations = [
        #migrations.RemoveConstraint(
        #    model_name="permisos",
        #    name="unique_rol_vista",
        #),
        ##    model_name="permisos",
        ##),
        migrations.AddField(
            model_name="permisos",
            name="accion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.accion",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="permisos",
            constraint=models.UniqueConstraint(
                fields=("rol", "vista", "accion"), name="unique_rol_vista_accion_p"
            ),
        ),
    ]
