# Generated by Django 5.0.6 on 2024-06-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_permisos_unique_rol_vista_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="permisos",
            name="unique_rol_vista",
        ),
        migrations.RemoveConstraint(
            model_name="permisos",
            name="unique_rol_vistaa",
        ),
    ]
