# Generated by Django 5.0.6 on 2024-06-11 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_permisos_pantalla"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permisos",
            name="pantalla",
        ),
        migrations.CreateModel(
            name="PantallaPermisos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pantalla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.pantalla",
                    ),
                ),
                (
                    "permiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.permisos",
                    ),
                ),
            ],
            options={
                "unique_together": {("pantalla", "permiso")},
            },
        ),
        migrations.AddField(
            model_name="permisos",
            name="pantallas",
            field=models.ManyToManyField(
                through="accounts.PantallaPermisos", to="accounts.pantalla"
            ),
        ),
    ]
