# Generated by Django 4.2.7 on 2023-12-04 14:26
from django.db import migrations

def create_roles(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    roles = [
        (1, 'ADMIN'),
        (2, 'AGENTE_CAT'),
        (3, 'AUDITORIA'),
        (4, 'AUXCUMP'),
        (5, 'AUXFIDU'),
        (6, 'AUXPRIESGO'),
        (7, 'AUXTES'),
        (8, 'COPERFIDU'),
        (9, 'CORCUMP'),
        (10, 'NEGFID'),
        (11, 'OPER'),
        (12, 'AGENTE_FIDECOMISOS'),
        (13, 'EMPLEADO')
    ]
    for role_id, role_name in roles:
        Role.objects.create(id=role_id, name=role_name)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role_remove_profile_role_profile_rol'),
    ]

    operations = [
         migrations.RunPython(create_roles),
    ]
