# Generated by Django 4.2.7 on 2023-12-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_view_permisos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permisos',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='permisos',
            constraint=models.UniqueConstraint(fields=('role', 'view'), name='unique_role_view'),
        ),
    ]
